/**
 * ScriptGenerator — client-side, unified main-loop + INF PLAY generator
 *
 * Produces `SimplePlayer.Round[]` from a `CourseBundle` + position +
 * mode. Replaces the three current pipelines:
 *
 *   - /api/courses/:code/cycles + backendCyclesToRounds   (main loop)
 *   - /api/courses/:code/infplay-cycles + infPlayCyclesToRounds (INF PLAY)
 *   - generateLearningScript (CourseExplorer admin)  — KEEPS this one;
 *     the admin path stays Supabase-driven for now.
 *
 * The output shape MUST match `SimplePlayer.Round` from
 * `packages/player-vue/src/playback/SimplePlayer.ts` so the player
 * consumes it unchanged via `simplePlayer.initialize(rounds)` /
 * `simplePlayer.appendRounds(rounds)`.
 *
 * Per-cycle audio URLs are constructed against `/api/audio/${id}` —
 * AudioCache transparently intercepts these via its blob-URL handoff
 * when the file is locally cached, otherwise the SW CacheFirst plus
 * the proxy serve.
 */

import type { Round } from '../playback/SimplePlayer'
import type { CourseBundle } from '../types/courseBundle'

// ============================================================================
// MODE + POSITION
// ============================================================================

/**
 * `main`    — script generated from the round-map starting at a given
 *   LEGO. Includes intro/debut/builds/uses for the focal LEGO plus
 *   Fibonacci spaced-rep reviews (USE phrases from older LEGOs).
 *
 * `infplay` — script generated by sampling at a given INF PLAY round
 *   number. Spaced-rep against fib offsets (1, 2, 3, 5, 8, 13, 21,
 *   34, 55, 89) into the main loop plus random USE LEGOs to fill the
 *   round to ~22 cycles.
 */
export type ScriptMode = 'main' | 'infplay'

/** Position for main-loop generation. */
export interface MainPosition {
  mode: 'main'
  /** Start at the LEGO with this id. */
  fromLegoId: string
}

/** Position for INF PLAY generation. */
export interface InfPlayPosition {
  mode: 'infplay'
  /**
   * 1-based INF PLAY round number. Round 1 = first round past main
   * loop; round 2 = second round past main loop; etc. Drives the
   * spaced-rep math via `absoluteRound = mainLoopCount + infRound`.
   */
  fromInfRound: number
}

export type ScriptPosition = MainPosition | InfPlayPosition

// ============================================================================
// GENERATION OPTIONS
// ============================================================================

export interface GenerateScriptOptions {
  bundle: CourseBundle
  position: ScriptPosition

  /**
   * How many rounds to generate. Default 15 — matches the existing
   * /cycles BOOTSTRAP_LIMIT. Caller can request more for offline-eager
   * paths (e.g. listening mode pre-bake).
   */
  roundLimit?: number

  /**
   * URL builder for audio refs. Defaults to `/api/audio/${id}`. Test
   * paths can substitute (e.g. fixture URLs).
   */
  audioUrl?: (id: string) => string

  /**
   * Optional RNG injection for INF PLAY's random USE sampling.
   * Defaults to `Math.random`. Tests pass a seeded RNG so the output
   * is deterministic.
   */
  random?: () => number
}

// ============================================================================
// GENERATION RESULT
// ============================================================================

export interface GenerateScriptResult {
  rounds: Round[]
  /**
   * Pagination cursor for the NEXT call:
   *   - main:    legoId where the next batch should start, or null at
   *              course end.
   *   - infplay: next INF PLAY round number (always defined; INF PLAY
   *              never ends).
   */
  next: { mode: 'main'; legoId: string | null } | { mode: 'infplay'; infRound: number }
}

// ============================================================================
// GENERATOR FUNCTION
// ============================================================================

/**
 * Pure function (modulo `random` injection). No I/O, no Supabase, no
 * fetch — the bundle is already in memory. Suitable for synchronous
 * use from the prefetcher and the bootstrap path alike.
 *
 * Implementation notes for the agent building this:
 *
 *   - Per-LEGO cycle assembly (main loop) follows the same shape as
 *     `api/courses/[code]/cycles.ts`'s `buildLegoCycles`: intro →
 *     debut → BUILDs → USEs. Translate from `CourseBundle` types,
 *     emit `SimplePlayer.Round`/`Cycle` shapes.
 *
 *   - Spaced rep for main loop: walk Fibonacci offsets back from the
 *     current round, look up the LEGO at (roundNumber - offset) via
 *     the bundle.roundMap, pull its USE phrases (3 for N-1, 1 for
 *     others — see DEFAULT_SCRIPT_SHAPE in
 *     `providers/generateLearningScript.ts`).
 *
 *   - INF PLAY assembly mirrors `api/courses/[code]/infplay-cycles.ts`'s
 *     in-memory algorithm. Don't reinvent — port the algorithm.
 *
 *   - pauseDuration for non-intro cycles uses
 *     `playback/computePauseDuration.ts` with DEFAULT_NORMAL from
 *     `useAlgorithmConfig`. Matches `backendCyclesToRounds.toPlayerCycle`.
 *
 *   - Intros get pauseDuration: 0 and lingerMs: 2000 (per the existing
 *     adapter). The intro cycle uses presentation_audio for the prompt
 *     slot, target1/target2 for the voice slots.
 *
 *   - When a phrase or LEGO is missing required audio (known + target1
 *     + target2 for normal cycles; target1 + target2 for intros), the
 *     cycle is dropped — same skip-policy as the existing adapter.
 *     The round still plays the rest.
 */
export type GenerateScript = (opts: GenerateScriptOptions) => GenerateScriptResult
