import type { CapacitorConfig } from '@capacitor/cli'

/**
 * Capacitor wrapper for the SSi learner app — Android and iOS, DEBUG ONLY.
 *
 * THE SHELL IS A WEBVIEW ONTO THE DEPLOYMENT, NOT A BUNDLE. Tom's ruling,
 * 2026-09-08: the APK stops carrying a frozen copy of the web app and loads
 * it from a real origin instead. That supersedes the 2026-09-04 ruling written
 * up in src/platform/buildStaleness.ts, which kept the bundle and cured the
 * resulting silence with a visible line. The reason it was overturned is that
 * a bundled APK's "Tap to update" can never fetch new web code — the button
 * lied — and needing a network to fetch an update is a property of updating
 * rather than a cost of loading remotely. What covers the learner BETWEEN
 * updates is the service worker, which now runs inside the WebView because
 * the shell it precaches is the deployment's own shell. See
 * src/platform/capabilities.ts.
 *
 * ONE LINE SWITCHES THE ORIGIN. `SHELL_ORIGIN` below is the whole switch, and
 * as of Tom's ruling on 2026-09-08 it points at PRODUCTION — "We also want the
 * Android app to be serving main now right? Now we've tested it." The staging
 * wrap was the proving ground and it proved; the shell is now a window onto
 * https://saysomethingin.app. Export SSI_SHELL_ORIGIN before building to point
 * one build somewhere else, e.g. back at staging for a field test.
 *
 * APPLICATION ID IS DELIBERATELY LOCAL. `com.saysomethingin.devwrap` is a
 * throwaway dev identifier. It is NOT `com.automagic.a3f`, the live published
 * listing — whether the real build ever takes that id, which would update the
 * app under every existing user of it, is Tom's decision and is irreversible.
 * Nothing here presumes it.
 */

/** The deployment this shell is a window onto. Production, by Tom's ruling. */
const SHELL_ORIGIN = (process.env.SSI_SHELL_ORIGIN || 'https://saysomethingin.app').replace(/\/+$/, '')

const config: CapacitorConfig = {
  appId: 'com.saysomethingin.devwrap',
  appName: 'SSi (dev wrap)',
  /**
   * NOT the app. With `server.url` set the WebView never reads these assets;
   * `webDir` still has to exist because `cap sync` copies it, so it points at
   * a one-page holding notice generated by scripts/write-shell-web.sh. The
   * old value was 'dist', which put 823 frozen files of web app inside the APK
   * that nothing loaded and that any future reader would mistake for the code
   * actually running. It was called 'android-shell-web' until iOS started
   * copying the same directory; a name that says android on a path both
   * platforms read is a name that misleads.
   */
  webDir: 'shell-web',
  server: {
    /**
     * The WebView's own origin is now the deployment's origin, so every
     * `/api/...` path is same-origin again and the platform seam's apiOrigin
     * goes back to the empty string it has on the web. The CORS allowlisting
     * of https://localhost stays deployed and stops being load-bearing here.
     */
    url: SHELL_ORIGIN,
    cleartext: false,
  },
  android: {
    // Debug builds only. Cleartext stays off — the deployment is https.
    allowMixedContent: false,
    /**
     * HOW THE APP KNOWS IT IS IN THE SHELL. The old build stamped
     * `window.__SSI_PLATFORM__` into the index.html it bundled. Loading the
     * deployment's index.html instead means there is nothing of ours to stamp,
     * so the shell says who it is in the user agent and
     * src/platform/capabilities.ts reads it there. Keep this string in step
     * with SHELL_UA_MARKER in that file — its test pins both.
     */
    appendUserAgent: 'SSiShell/android',
  },
  ios: {
    /**
     * THE MICROPHONE IS WHY THIS PLATFORM WAS EVER IN DOUBT, and it is fine.
     * getUserMedia reached WKWebView in iOS 14.3; since iOS 15 the gate is
     * WKUIDelegate's requestMediaCapturePermissionFor, and Capacitor 8
     * implements it with an unconditional `.grant` — no origin test, nothing
     * for us to write. The origin only has to be a SECURE context, which
     * https://saysomethingin.app is. The failure reports in the wild are all
     * capacitor://localhost:8080 and file:// — so loading remotely is the
     * SAFER posture on iOS, not the riskier one. What the OS still requires is
     * NSMicrophoneUsageDescription in ios/App/App/Info.plist, and its absence
     * is a process kill rather than a denial. See
     * the repo-root docs/ios-remote-origin-microphone-2026-09-09.md. UNVERIFIED on a device.
     */

    /**
     * HOW THE APP KNOWS IT IS IN THE SHELL — the iOS half of the android
     * marker above. Keep in step with SHELL_UA_MARKER in
     * src/platform/capabilities.ts; its test pins both strings.
     */
    appendUserAgent: 'SSiShell/ios',
    /**
     * FALSE IS LOAD-BEARING HERE, not decoration. App-bound domains would cap
     * this WebView to the origins named in a WKAppBoundDomains Info.plist key,
     * and a shell whose whole content is a remote origin is exactly what that
     * restriction exists to stop. It is Capacitor's default and there is no
     * WKAppBoundDomains key in our plist, so nothing is on — written down so
     * that adding one later is a visible decision rather than a silent break.
     */
    limitsNavigationsToAppBoundDomains: false,
    /**
     * The deployment already draws its own chrome under the notch and the home
     * indicator — index.html carries viewport-fit=cover, so env(safe-area-*)
     * is live and the app's CSS reads it. 'never' keeps UIKit from adding a
     * second inset on top of that and double-counting it.
     */
    contentInset: 'never',
    /**
     * Dev wrap: lets Safari's Web Inspector attach to the WebView from the Mac
     * over USB. On iOS 16.4+ a WKWebView is inspectable only if it says so.
     */
    webContentsDebuggingEnabled: true,
  },
  plugins: {
    /**
     * INSET HANDLING IS DECLARED, NOT INHERITED. 'css' is already Capacitor
     * 8's default, and it is written down here because the app's whole
     * bottom-chrome clearance depends on it: with 'css' the SystemBars plugin
     * sets `--safe-area-inset-*` on documentElement in dp, which is the only
     * source that reports correctly in BOTH of its postures — the one where
     * it pads the WebView out of the system bars, where env() legitimately
     * reads 0, and the one where the WebView draws edge-to-edge and env() is
     * live. 'disable' would leave the app with no inset source at all and the
     * bottom controls back inside the navigation bar.
     *
     * ANDROID ONLY. Capacitor 8's SystemBars.swift exposes setStyle, show,
     * hide and setAnimation and nothing else — no insetsHandling, no CSS
     * custom properties — so iOS ignores this key entirely and falls through
     * to native env(), which shellSafeArea.measureInsets() reads via a probe
     * element. That is the iOS convention and it is already what the app
     * wants, so iOS needs no inset work of its own.
     *
     * See src/platform/shellSafeArea.ts and --shell-nav-clearance in
     * src/styles/design-tokens.css.
     */
    SystemBars: {
      insetsHandling: 'css',
    },
  },
}

export default config
