import type { CapacitorConfig } from '@capacitor/cli'

/**
 * Capacitor wrapper for the SSi learner app — Android, DEBUG ONLY.
 *
 * THE SHELL IS A WEBVIEW ONTO THE DEPLOYMENT, NOT A BUNDLE. Tom's ruling,
 * 2026-09-08: the APK stops carrying a frozen copy of the web app and loads
 * it from a real origin instead. That supersedes the 2026-09-04 ruling written
 * up in src/platform/buildStaleness.ts, which kept the bundle and cured the
 * resulting silence with a visible line. The reason it was overturned is that
 * a bundled APK's "Tap to update" can never fetch new web code — the button
 * lied — and needing a network to fetch an update is a property of updating
 * rather than a cost of loading remotely. What covers the learner BETWEEN
 * updates is the service worker, which now runs inside the WebView because
 * the shell it precaches is the deployment's own shell. See
 * src/platform/capabilities.ts.
 *
 * ONE LINE SWITCHES THE ORIGIN, AND ITS DEFAULT IS STAGING. Tom's ruling,
 * 2026-09-10, overturning the default set on 2026-09-08: production is for
 * live learners, and the only honest reason to test there is to fix a problem
 * that is live — never to compare builds or platforms. So a build that lands
 * on production BY ACCIDENT is always wrong, and an unset SSI_SHELL_ORIGIN
 * must therefore yield staging. Production is still one command away, but it
 * has to be asked for out loud:
 *
 *     SSI_SHELL_ORIGIN=https://saysomethingin.app scripts/build-android-apk.sh
 *     scripts/build-android-apk.sh https://saysomethingin.app   # same thing
 *
 * This costs a forgetful builder nothing worse than a tester on staging, which
 * is where a tester belongs. The reverse mistake put Colombo on production
 * without anyone choosing it.
 *
 * APPLICATION ID IS DELIBERATELY LOCAL. `com.saysomethingin.devwrap` is a
 * throwaway dev identifier. It is NOT `com.automagic.a3f`, the live published
 * listing — whether the real build ever takes that id, which would update the
 * app under every existing user of it, is Tom's decision and is irreversible.
 * Nothing here presumes it.
 */

/**
 * The deployment this shell is a window onto. STAGING unless someone says
 * otherwise — see the ruling above. scripts/build-android-apk.sh reads this
 * very line for its own default, so the two cannot drift apart.
 */
const SHELL_DEFAULT_ORIGIN = 'https://staging.saysomethingin.app'
const SHELL_ORIGIN = (process.env.SSI_SHELL_ORIGIN || SHELL_DEFAULT_ORIGIN).replace(/\/+$/, '')

const config: CapacitorConfig = {
  appId: 'com.saysomethingin.devwrap',
  appName: 'SSi (dev wrap)',
  /**
   * NOT the app. With `server.url` set the WebView never reads these assets;
   * `webDir` still has to exist because `cap sync` copies it, so it points at
   * a one-page holding notice generated by scripts/build-android-apk.sh. The
   * old value was 'dist', which put 823 frozen files of web app inside the APK
   * that nothing loaded and that any future reader would mistake for the code
   * actually running.
   */
  webDir: 'android-shell-web',
  server: {
    /**
     * The WebView's own origin is now the deployment's origin, so every
     * `/api/...` path is same-origin again and the platform seam's apiOrigin
     * goes back to the empty string it has on the web. The CORS allowlisting
     * of https://localhost stays deployed and stops being load-bearing here.
     */
    url: SHELL_ORIGIN,
    cleartext: false,
  },
  android: {
    // Debug builds only. Cleartext stays off — the deployment is https.
    allowMixedContent: false,
    /**
     * HOW THE APP KNOWS IT IS IN THE SHELL. The old build stamped
     * `window.__SSI_PLATFORM__` into the index.html it bundled. Loading the
     * deployment's index.html instead means there is nothing of ours to stamp,
     * so the shell says who it is in the user agent and
     * src/platform/capabilities.ts reads it there. Keep this string in step
     * with SHELL_UA_MARKER in that file — its test pins both.
     */
    appendUserAgent: 'SSiShell/android',
  },
  plugins: {
    /**
     * INSET HANDLING IS DECLARED, NOT INHERITED. 'css' is already Capacitor
     * 8's default, and it is written down here because the app's whole
     * bottom-chrome clearance depends on it: with 'css' the SystemBars plugin
     * sets `--safe-area-inset-*` on documentElement in dp, which is the only
     * source that reports correctly in BOTH of its postures — the one where
     * it pads the WebView out of the system bars, where env() legitimately
     * reads 0, and the one where the WebView draws edge-to-edge and env() is
     * live. 'disable' would leave the app with no inset source at all and the
     * bottom controls back inside the navigation bar.
     *
     * See src/platform/shellSafeArea.ts and --shell-nav-clearance in
     * src/styles/design-tokens.css.
     */
    SystemBars: {
      insetsHandling: 'css',
    },
  },
}

export default config
