import { describe, it, expect } from 'vitest'
import { parseTrainNote, TRAIN_RELEASE_NOTES } from './trainReleaseNotes'
import { mergeReleaseNotes, type ReleaseNote } from './useReleaseNotes'

const FINAL = `<!-- release-notes:header -->
# Release notes — shipped 2026-07-30

Live on [saysomethingin.app](https://saysomethingin.app) since 2026-07-30. 150 commits, promoted from \`staging\` at \`ce7d2f7\`.

Up to three headline features, then the fixes. Generated by \`tools/release-train/release-notes.mjs\`.
<!-- /release-notes:header -->

## What's new

- Switching course is near-instant.

## Fixes

- The play button no longer falls out of step.
`

const DRAFT = FINAL.replace(
  '# Release notes — shipped 2026-07-30',
  '# Release notes — DRAFT for the next ship',
)

describe('parseTrainNote', () => {
  it('parses a finalised note into dated bullets', () => {
    const note = parseTrainNote(FINAL)!
    expect(note.id).toBe('train-2026-07-30')
    expect(note.released_at.slice(0, 10)).toBe('2026-07-30')
    expect(note.bullets).toEqual([
      'Switching course is near-instant.',
      'The play button no longer falls out of step.',
    ])
  })

  it('NEVER surfaces a draft — an unshipped Friday must not reach learners', () => {
    expect(parseTrainNote(DRAFT)).toBeNull()
  })

  it('leaves no plumbing in the learner-facing bullets', () => {
    const joined = parseTrainNote(FINAL)!.bullets.join(' ')
    expect(joined).not.toMatch(/release-notes:header|release-notes\.mjs|promoted from/)
  })

  it('blanks version so the update nudge cannot false-fire on a staging sha', () => {
    expect(parseTrainNote(FINAL)!.version).toBe('')
  })

  it('strips a hand-left draft-only coverage block', () => {
    const withCoverage = FINAL.replace(
      '## Fixes',
      '<!-- release-notes:draft-only -->\n## Draft-only: coverage\n\n- dropped: some refactor\n<!-- /release-notes:draft-only -->\n\n## Fixes',
    )
    expect(parseTrainNote(withCoverage)!.bullets).not.toContain('dropped: some refactor')
  })

  it('ignores a file with no header block, and a final with no bullets', () => {
    expect(parseTrainNote('# Just some markdown\n\n- a bullet\n')).toBeNull()
    expect(parseTrainNote(FINAL.split('## What\'s new')[0])).toBeNull()
  })
})

describe('TRAIN_RELEASE_NOTES (the real bundled files)', () => {
  it('bundles only shipped notes, newest first, each with bullets', () => {
    // Non-empty on purpose: this is the wiring test. If the glob ever stops
    // resolving tools/release-train/notes/, the panel goes quiet and nobody
    // notices — so fail here instead.
    expect(TRAIN_RELEASE_NOTES.length).toBeGreaterThan(0)
    for (const note of TRAIN_RELEASE_NOTES) {
      expect(note.id).toMatch(/^train-\d{4}-\d{2}-\d{2}$/)
      expect(note.bullets.length).toBeGreaterThan(0)
      expect(note.is_published).toBe(true)
    }
    const dates = TRAIN_RELEASE_NOTES.map((n) => n.released_at)
    expect([...dates].sort().reverse()).toEqual(dates)
  })
})

describe('mergeReleaseNotes', () => {
  const authored: ReleaseNote = {
    id: 'db-1', version: 'abc1234', released_at: '2026-07-30T09:00:00.000Z',
    headline: 'Hand written', bullets: ['authored'], is_published: true,
  }
  const train: ReleaseNote = {
    id: 'train-2026-07-30', version: '', released_at: '2026-07-30T00:00:00.000Z',
    headline: null, bullets: ['generated'], is_published: true,
  }
  const older: ReleaseNote = { ...train, id: 'train-2026-07-23', released_at: '2026-07-23T00:00:00.000Z' }

  it('gives the day to the hand-authored row', () => {
    expect(mergeReleaseNotes([authored], [train], 5).map((n) => n.id)).toEqual(['db-1'])
  })

  it('keeps train notes for days nobody wrote up, newest first', () => {
    expect(mergeReleaseNotes([authored], [train, older], 5).map((n) => n.id))
      .toEqual(['db-1', 'train-2026-07-23'])
  })

  it('honours the limit', () => {
    expect(mergeReleaseNotes([], [train, older], 1).map((n) => n.id)).toEqual(['train-2026-07-30'])
  })
})

describe('the catch-all section', () => {
  it('reads "Other stuff and bug fixes" — the heading the generator actually writes', () => {
    // release-notes.mjs renderFinal emits "## Other stuff and bug fixes". The parser used to
    // look only for "## Fixes", so the whole catch-all went missing from every note.
    const note = parseTrainNote([
      '<!-- release-notes:header -->',
      '# Release notes — shipped 2026-08-29',
      '<!-- /release-notes:header -->',
      '',
      "## What's new",
      '',
      '- A big thing a learner notices.',
      '',
      '## Other stuff and bug fixes',
      '',
      '- A small thing a learner notices.',
      '- Another small thing.',
      '',
    ].join('\n'))
    expect(note).not.toBeNull()
    expect(note!.bullets).toEqual([
      'A big thing a learner notices.',
      'A small thing a learner notices.',
      'Another small thing.',
    ])
  })
})
