/**
 * trainReleaseNotes — the release train's notes, bundled at BUILD TIME.
 *
 * The Friday train already writes honest, learner-facing notes to
 * `tools/release-train/notes/<date>.md` (see `docs/RELEASE-TRAIN.md`). They were
 * reaching nobody: the Settings "What's new" panel only ever read the
 * admin-curated `release_notes` table in Supabase. This module closes that gap by
 * importing the notes files straight into the bundle — no endpoint, no table, no
 * runtime fetch, nothing to keep in sync. The bundle IS the delivery.
 *
 * Two rules the parser exists to enforce:
 *  1. FINALS ONLY. A draft ("# Release notes — DRAFT for the next ship") describes
 *     a ship that has not happened. Learners must never see it, so only a header
 *     stamped "shipped <date>" produces an entry.
 *  2. NO PLUMBING. The header block, the draft-only coverage section and the
 *     "Generated by ..." attribution are stripped — learners get the bullets.
 */

const HEADER_OPEN = '<!-- release-notes:header -->'
const HEADER_CLOSE = '<!-- /release-notes:header -->'
const DRAFT_OPEN = '<!-- release-notes:draft-only -->'
const DRAFT_CLOSE = '<!-- /release-notes:draft-only -->'

/** Matches ONLY a finalised header — `--finalize` stamps "shipped <date>". */
const SHIPPED_RE = /^#\s*Release notes\s*—\s*shipped\s+(\d{4}-\d{2}-\d{2})\s*$/m

export interface TrainReleaseNote {
  id: string
  version: string
  released_at: string
  headline: string | null
  bullets: string[]
  is_published: boolean
}

function sectionBullets(body: string, heading: string): string[] {
  const lines = body.split('\n')
  const start = lines.findIndex((l) => l.trim().toLowerCase() === `## ${heading}`.toLowerCase())
  if (start === -1) return []
  const out: string[] = []
  for (const line of lines.slice(start + 1)) {
    if (line.startsWith('## ')) break
    const m = /^\s*-\s+(.*\S)\s*$/.exec(line)
    if (m) out.push(m[1])
  }
  return out
}

/**
 * Parse one notes file. Returns null for drafts, unparseable files, and finals
 * that carry no bullets at all (an empty "What's new" is not worth a row).
 */
export function parseTrainNote(source: string): TrainReleaseNote | null {
  const headerEnd = source.indexOf(HEADER_CLOSE)
  const header = headerEnd === -1 ? '' : source.slice(0, headerEnd)
  if (!header.includes(HEADER_OPEN)) return null

  const shipped = SHIPPED_RE.exec(header)
  if (!shipped) return null // draft, or a header shape we don't recognise — say nothing
  const shipDate = shipped[1]

  let body = source.slice(headerEnd + HEADER_CLOSE.length)
  // Belt and braces: the draft-only coverage block is stripped at finalise time,
  // but a hand-edited file could still carry one.
  for (;;) {
    const a = body.indexOf(DRAFT_OPEN)
    const b = body.indexOf(DRAFT_CLOSE)
    if (a === -1 || b === -1 || b < a) break
    body = body.slice(0, a) + body.slice(b + DRAFT_CLOSE.length)
  }

  // Both catch-all headings. The generator writes "## Other stuff and bug fixes"
  // (release-notes.mjs renderFinal) and has done since July; this parser only looked for
  // "## Fixes", so every catch-all bullet the train has ever written was silently dropped and
  // learners saw the three headlines alone. Found live on 2026-08-29.
  const bullets = [
    ...sectionBullets(body, "What's new"),
    ...sectionBullets(body, 'Other stuff and bug fixes'),
    ...sectionBullets(body, 'Fixes'),
  ]
  if (bullets.length === 0) return null

  return {
    id: `train-${shipDate}`,
    // Deliberately blank. `version` drives the Settings "Update available" nudge by
    // SHA-prefix comparison against the running build — but the sha in these notes is
    // the STAGING head, never the main merge commit the browser is running, so any
    // value here would false-fire the nudge forever. The date carries the meaning.
    version: '',
    released_at: `${shipDate}T00:00:00.000Z`,
    headline: null,
    bullets,
    is_published: true,
  }
}

// Eager + raw: the markdown never reaches the client as markdown, only the parsed
// bullets do, and the whole set is a few hundred bytes per ship.
const files = import.meta.glob('../../../../tools/release-train/notes/*.md', {
  eager: true,
  query: '?raw',
  import: 'default',
}) as Record<string, string>

/** Every SHIPPED note the train has written, newest first. */
export const TRAIN_RELEASE_NOTES: TrainReleaseNote[] = Object.entries(files)
  .map(([, source]) => parseTrainNote(source))
  .filter((n): n is TrainReleaseNote => n !== null)
  .sort((a, b) => b.released_at.localeCompare(a.released_at))
