-- ============================================
-- Disable RLS on ALL tables
-- ============================================
-- RLS was silently blocking queries (returning empty results with no error).
-- Disabling globally so the system works transparently.
-- RLS can be re-added gradually once features are proven working.
--
-- Date: 2026-03-26

-- Content tables
ALTER TABLE IF EXISTS courses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS course_seeds DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS course_legos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS course_practice_phrases DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audio_samples DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lego_introductions DISABLE ROW LEVEL SECURITY;

-- Learner tables
ALTER TABLE IF EXISTS learners DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS course_enrollments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lego_progress DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS seed_progress DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS response_metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS spike_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS learner_baselines DISABLE ROW LEVEL SECURITY;

-- Schools tables
ALTER TABLE IF EXISTS regions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS invite_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS govt_admins DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS schools DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS class_sessions DISABLE ROW LEVEL SECURITY;

-- Gamification tables
ALTER TABLE IF EXISTS learner_points DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS learner_milestones DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS daily_contributions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS gamification_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS evolution_levels DISABLE ROW LEVEL SECURITY;

-- Subscription & entitlement tables
ALTER TABLE IF EXISTS subscriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS entitlement_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_entitlements DISABLE ROW LEVEL SECURITY;

-- Analytics & config tables
ALTER TABLE IF EXISTS audio_plays DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS algorithm_config DISABLE ROW LEVEL SECURITY;
