export { setSchoolsClient, getSchoolsClient } from './client'
export { useSchoolContext } from './useSchoolContext'
export type { EducationalRole, SchoolUser } from './useSchoolContext'
export { useSchoolData } from './useSchoolData'
export { useClassesData } from './useClassesData'
export type { ClassSession } from './useClassesData'
export { useTeachersData } from './useTeachersData'
export { useStudentsData } from './useStudentsData'
export { useAnalyticsData } from './useAnalyticsData'
