export { setSchoolsClient, getSchoolsClient } from './client'
export { useGodMode } from './useGodMode'
export type { EducationalRole, GodModeUser } from './useGodMode'
export { useSchoolData } from './useSchoolData'
export { useClassesData } from './useClassesData'
export type { ClassSession } from './useClassesData'
export { useTeachersData } from './useTeachersData'
export { useStudentsData } from './useStudentsData'
export { useAnalyticsData } from './useAnalyticsData'
