/**
 * The snapshot-drift guard.
 *
 * `supabase/schema.sql` is this repo's DECLARED source of truth for the shape
 * of the live database — every agent and every human reasons about the DB from
 * that file. It is regenerated by hand (`./supabase/snapshot-schema.sh`)
 * after a live DB change, and on 2026-09-05 it
 * was found four merges out of date: `course_sectors` and `enrollment_threads`
 * were live and queried by `api/courses/[code]/sectors.ts` and
 * `api/me/threads.ts`, and absent from the snapshot. Nothing in CI noticed.
 *
 * This test is the cheapest honest guard that needs NO database credential, so
 * it can run in `verify.yml` where a live-DB comparison cannot: every relation
 * the shipping code names in a PostgREST `.from('…')` call must be declared in
 * the snapshot. A table that reaches production without a regenerated snapshot
 * fails here by name.
 *
 * What it CANNOT see: a table that exists live but nothing queries yet, or a
 * column/policy/index difference. Those need the live database — see
 * `supabase/check-schema-drift.sh`, which is deliberately not in CI because
 * wiring it would mean putting a database credential next to the repo.
 */
import { describe, it, expect } from 'vitest'
import { readFileSync, readdirSync, statSync } from 'node:fs'
import { join, resolve } from 'node:path'

const REPO = resolve(__dirname, '..')

/** Dirs holding code that talks to the live database. */
const SCANNED = ['api', 'packages/player-vue/src']

/** Relation names declared by the committed snapshot (tables + views). */
function declaredRelations(): Set<string> {
  const sql = readFileSync(join(REPO, 'supabase/schema.sql'), 'utf8')
  const re = /^CREATE (?:TABLE|VIEW|MATERIALIZED VIEW) (?:IF NOT EXISTS )?public\.([a-zA-Z0-9_]+)/gm
  return new Set([...sql.matchAll(re)].map((m) => m[1]))
}

function sourceFiles(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    if (entry === 'node_modules' || entry === 'dist') continue
    const p = join(dir, entry)
    if (statSync(p).isDirectory()) sourceFiles(p, out)
    // Test files are skipped: their in-memory fixtures name relations that are
    // deliberately fake, which would be noise rather than drift.
    else if (/\.(ts|vue)$/.test(entry) && !/\.test\.ts$/.test(entry)) out.push(p)
  }
  return out
}

/** Every `.from('relation')` a shipping source file names, with its location. */
function queriedRelations(): Map<string, string> {
  const found = new Map<string, string>()
  for (const dir of SCANNED) {
    for (const file of sourceFiles(join(REPO, dir))) {
      const src = readFileSync(file, 'utf8')
      for (const m of src.matchAll(/\.from\(\s*'([a-z_][a-z0-9_]*)'/g)) {
        if (!found.has(m[1])) found.set(m[1], file.slice(REPO.length + 1))
      }
    }
  }
  return found
}

describe('supabase/schema.sql tracks the code that queries the database', () => {
  it('declares every relation the shipping code selects from', () => {
    const declared = declaredRelations()
    const missing = [...queriedRelations()]
      .filter(([rel]) => !declared.has(rel))
      .map(([rel, file]) => `${rel}  (queried by ${file})`)

    expect(
      missing,
      missing.length
        ? `supabase/schema.sql is out of date — it does not declare relations that live code queries.\n` +
          `Regenerate it:  ./supabase/snapshot-schema.sh\n\n` +
          missing.map((m) => `  - ${m}`).join('\n') + '\n'
        : '',
    ).toEqual([])
  })

  it('finds relations to check at all (guards against the scan silently matching nothing)', () => {
    expect(queriedRelations().size).toBeGreaterThan(50)
  })
})
